# Local Get 
GET http://localhost:8080/contact/
GET http://localhost:8080/contact/6633cdd175e28dc085498ca0

# Render GET
https://cse341-15dr.onrender.com/contact
https://cse341-15dr.onrender.com/contact/6633cdd175e28dc085498ca0